package modelo;
// Generated 15-nov-2018 0:20:26 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TAlumno generated by hbm2java
 */
public class TAlumno  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Date fechaNac;

    public TAlumno() {
    }

    public TAlumno(String nombre, Date fechaNac) {
       this.nombre = nombre;
       this.fechaNac = fechaNac;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }




}


