package modelo;
// Generated 15-nov-2018 0:20:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TAsignatura generated by hbm2java
 */
public class TAsignatura  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private TAsignaturacolegio TAsignaturacolegio;
     private Set TMantenedorprofes = new HashSet(0);

    public TAsignatura() {
    }

	
    public TAsignatura(String nombre) {
        this.nombre = nombre;
    }
    public TAsignatura(String nombre, TAsignaturacolegio TAsignaturacolegio, Set TMantenedorprofes) {
       this.nombre = nombre;
       this.TAsignaturacolegio = TAsignaturacolegio;
       this.TMantenedorprofes = TMantenedorprofes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public TAsignaturacolegio getTAsignaturacolegio() {
        return this.TAsignaturacolegio;
    }
    
    public void setTAsignaturacolegio(TAsignaturacolegio TAsignaturacolegio) {
        this.TAsignaturacolegio = TAsignaturacolegio;
    }
    public Set getTMantenedorprofes() {
        return this.TMantenedorprofes;
    }
    
    public void setTMantenedorprofes(Set TMantenedorprofes) {
        this.TMantenedorprofes = TMantenedorprofes;
    }




}


