package modelo;
// Generated 15-nov-2018 0:20:26 by Hibernate Tools 4.3.1



/**
 * TAsignaturacolegio generated by hbm2java
 */
public class TAsignaturacolegio  implements java.io.Serializable {


     private int idAsignaturaFk;
     private TAsignatura TAsignatura;
     private TColegio TColegio;

    public TAsignaturacolegio() {
    }

    public TAsignaturacolegio(TAsignatura TAsignatura, TColegio TColegio) {
       this.TAsignatura = TAsignatura;
       this.TColegio = TColegio;
    }
   
    public int getIdAsignaturaFk() {
        return this.idAsignaturaFk;
    }
    
    public void setIdAsignaturaFk(int idAsignaturaFk) {
        this.idAsignaturaFk = idAsignaturaFk;
    }
    public TAsignatura getTAsignatura() {
        return this.TAsignatura;
    }
    
    public void setTAsignatura(TAsignatura TAsignatura) {
        this.TAsignatura = TAsignatura;
    }
    public TColegio getTColegio() {
        return this.TColegio;
    }
    
    public void setTColegio(TColegio TColegio) {
        this.TColegio = TColegio;
    }




}


