package modelo;
// Generated 15-nov-2018 0:20:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TColegio generated by hbm2java
 */
public class TColegio  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String direccion;
     private Set TAsignaturacolegios = new HashSet(0);

    public TColegio() {
    }

	
    public TColegio(String nombre, String direccion) {
        this.nombre = nombre;
        this.direccion = direccion;
    }
    public TColegio(String nombre, String direccion, Set TAsignaturacolegios) {
       this.nombre = nombre;
       this.direccion = direccion;
       this.TAsignaturacolegios = TAsignaturacolegios;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set getTAsignaturacolegios() {
        return this.TAsignaturacolegios;
    }
    
    public void setTAsignaturacolegios(Set TAsignaturacolegios) {
        this.TAsignaturacolegios = TAsignaturacolegios;
    }




}


