package modelo;
// Generated 15-nov-2018 0:20:26 by Hibernate Tools 4.3.1



/**
 * TMantenedorprofe generated by hbm2java
 */
public class TMantenedorprofe  implements java.io.Serializable {


     private int profesorIdFk;
     private TAsignatura TAsignatura;
     private TProfesor TProfesor;

    public TMantenedorprofe() {
    }

    public TMantenedorprofe(TAsignatura TAsignatura, TProfesor TProfesor) {
       this.TAsignatura = TAsignatura;
       this.TProfesor = TProfesor;
    }
   
    public int getProfesorIdFk() {
        return this.profesorIdFk;
    }
    
    public void setProfesorIdFk(int profesorIdFk) {
        this.profesorIdFk = profesorIdFk;
    }
    public TAsignatura getTAsignatura() {
        return this.TAsignatura;
    }
    
    public void setTAsignatura(TAsignatura TAsignatura) {
        this.TAsignatura = TAsignatura;
    }
    public TProfesor getTProfesor() {
        return this.TProfesor;
    }
    
    public void setTProfesor(TProfesor TProfesor) {
        this.TProfesor = TProfesor;
    }




}


