package modelo;
// Generated 15-nov-2018 0:20:26 by Hibernate Tools 4.3.1



/**
 * TNota generated by hbm2java
 */
public class TNota  implements java.io.Serializable {


     private int id;
     private double nota;

    public TNota() {
    }

    public TNota(int id, double nota) {
       this.id = id;
       this.nota = nota;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public double getNota() {
        return this.nota;
    }
    
    public void setNota(double nota) {
        this.nota = nota;
    }




}


